package catalog

import (
	"github.com/lindsaygelle/nook"
	"github.com/lindsaygelle/nook/game"
)

// gamesByCharacterID maps composed character identifiers to their canonical
// Animal Crossing game appearance history in release order.
var gamesByCharacterID = map[nook.Key][]nook.Game{
	"alligator:Alfonso": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"alligator:Alli": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"alligator:Boots": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"alligator:Del": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"alligator:Drago": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"alligator:Gayle": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"alligator:Liz": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"alligator:Pironkon": {
		game.DoubutsuNoMoriEPlus,
		game.NewHorizons,
		game.PocketCamp,
	},
	"alligator:Sly": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"alpaca:Cyrus": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"alpaca:Reese": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"anteater:Anabelle": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"anteater:Annalisa": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"anteater:Antonio": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"anteater:Cyrano": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"anteater:Lulu": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"anteater:Nosegay": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"anteater:Olaf": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"anteater:Pango": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"anteater:Snooty": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"anteater:Zoe": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewHorizons,
		game.PocketCamp,
	},
	"axolotl:DrShrunk": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"bear:Beardo": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Charlise": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Chow": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Curt": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Dozer": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"bear:Grizzly": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Groucho": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Ike": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bear:Klaus": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Megan": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"bear:Nate": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Paula": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Pinky": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Teddy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Tutu": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bear:Ursala": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bearcub:Aisle": {
		game.DoubutsuNoMoriEPlus,
	},
	"bearcub:Barold": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Bluebear": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Cheri": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Chester": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Cupcake": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"bearcub:Judy": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"bearcub:June": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bearcub:Kody": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Maple": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Marty": {
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bearcub:Murphy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bearcub:Olive": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bearcub:Pekoe": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Poko": {
		game.DoubutsuNoMoriEPlus,
	},
	"bearcub:Poncho": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Pudge": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Stitches": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Tammy": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bearcub:Vladimir": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"beaver:CJ": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"beaver:Chip": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Ace": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bird:Admiral": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bird:Anchovy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Beppe": {
		game.PocketCamp,
	},
	"bird:Carlo": {
		game.PocketCamp,
	},
	"bird:Flash": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
	},
	"bird:Giovanni": {
		game.PocketCamp,
	},
	"bird:Jacob": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bird:Jacques": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Jay": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Jitters": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Joe": {
		game.DoubutsuNoMoriEPlus,
	},
	"bird:Lucha": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:MadamRosa": {
		game.DoubutsuNoMoriEPlus,
	},
	"bird:Medli": {
		game.NewLeaf,
	},
	"bird:Midge": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Otis": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"bird:Peck": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Piper": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bird:Robin": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Shoukichi": {
		game.DoubutsuNoMoriEPlus,
	},
	"bird:Sparro": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Twiggy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bird:Twirp": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"boar:DaisyMae": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"boar:Joan": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"bull:Angus": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bull:Chuck": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"bull:Coach": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bull:Oxford": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"bull:Rodeo": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bull:Stu": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"bull:TBone": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bull:Vic": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"bull:Weldon": {
		game.DoubutsuNoMoriEPlus,
	},
	"camel:Saharah": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"cat:Ankha": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Blanca": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"cat:Bob": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Felicity": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Felyne": {
		game.NewLeaf,
		game.HappyHomeDesigner,
	},
	"cat:Kabuki": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Kaitlin": {
		game.WildWorld,
		game.CityFolk,
	},
	"cat:Katie": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Katt": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:KidCat": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Kiki": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Kitty": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Lolly": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Meow": {
		game.DoubutsuNoMoriEPlus,
	},
	"cat:Merry": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Mitzi": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Moe": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Monique": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Olivia": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Pierre": {
		game.DoubutsuNoMoriEPlus,
	},
	"cat:Punchy": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Purrl": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Raymond": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"cat:Rosie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Rover": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Rudy": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Stinky": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Tabby": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Tangy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cat:Tom": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chameleon:Flick": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"chameleon:Nat": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"chicken:Ava": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chicken:Becky": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chicken:Benedict": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chicken:Betty": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"chicken:Broffina": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chicken:Egbert": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chicken:Goose": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chicken:Hank": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"chicken:Hector": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"chicken:Ken": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chicken:Knox": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"chicken:Leigh": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"chicken:Plucky": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"chicken:Rhoda": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"cow:Belle": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"cow:Bessie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"cow:Carrot": {
		game.DoubutsuNoMoriEPlus,
	},
	"cow:Naomi": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cow:Norma": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"cow:Patty": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"cow:Petunia": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"cow:Tipper": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Bam": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Beau": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Bruce": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Chelsea": {
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"deer:Deirdre": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Diana": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Erik": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Fauna": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Fuchsia": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Lopez": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"deer:Zell": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dodo:Orville": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"dodo:Wilbur": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"dog:Bea": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"dog:Benjamin": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Biskit": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Bones": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Booker": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"dog:Bow": {
		game.DoubutsuNoMoriEPlus,
	},
	"dog:Butch": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Champagne": {
		game.DoubutsuNoMoriEPlus,
		game.NewHorizons,
		game.PocketCamp,
	},
	"dog:Cherry": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Cookie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Copper": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"dog:Daisy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Digby": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Goldie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Harriet": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Harvey": {
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"dog:Isabelle": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:KKSlider": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Lucky": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Mac": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Maddie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.PocketCamp,
	},
	"dog:Marcel": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Masa": {
		game.DoubutsuNoMoriEPlus,
	},
	"dog:Megumi": {
		game.DoubutsuNoMoriEPlus,
	},
	"dog:Portia": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Serena": {
		game.CityFolk,
	},
	"dog:Shep": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"dog:Walker": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Bill": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Deena": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Derwin": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Drake": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Freckles": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Fruity": {
		game.DoubutsuNoMoriEPlus,
	},
	"duck:Gloria": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Joey": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Ketchup": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"duck:Maelle": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Mallary": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Miranda": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Molly": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Pate": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Pompom": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Quillson": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Scoot": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"duck:Shinabiru": {
		game.DoubutsuNoMoriEPlus,
	},
	"duck:Weber": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"eagle:Amelia": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"eagle:Apollo": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"eagle:Avery": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"eagle:Buzz": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"eagle:Celia": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"eagle:Frank": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"eagle:Keaton": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"eagle:Pierce": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"eagle:Quetzal": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"eagle:Sterling": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"elephant:Axel": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"elephant:BigTop": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"elephant:Chai": {
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"elephant:Cyd": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"elephant:Dizzy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"elephant:Elina": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
	},
	"elephant:Ellie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"elephant:Eloise": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"elephant:Margie": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"elephant:Opal": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"elephant:Paolo": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"elephant:Tia": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"elephant:Tucker": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"fox:Redd": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frillneckedlizard:Frillard": {
		game.CityFolk,
	},
	"frog:Camofrog": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Cousteau": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Croque": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Diva": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Drift": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Emerald": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"frog:Frobert": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Gigi": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Henry": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Huck": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"frog:Jambette": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Jeremiah": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Lily": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Prince": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Puddles": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Raddle": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"frog:Ribbot": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"frog:Sunny": {
		game.DoubutsuNoMoriEPlus,
	},
	"frog:Tad": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"frog:WartJr": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"furseal:Phineas": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"giraffe:Gracie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"goat:Billy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"goat:Chevre": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"goat:Gruff": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"goat:Iggy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"goat:Kidd": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"goat:Nan": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"goat:Pashmina": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"goat:Sherb": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"goat:Sven": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"goat:Velma": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"gorilla:Al": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"gorilla:Boone": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"gorilla:Boyd": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"gorilla:Cesar": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"gorilla:Hans": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"gorilla:Jane": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"gorilla:Louie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.PocketCamp,
	},
	"gorilla:Peewee": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"gorilla:Rilla": {
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"gorilla:Rocket": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"gorilla:Violet": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"gorilla:Yodel": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
	},
	"gyroid:Lloid": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hamster:Apple": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hamster:Clay": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hamster:Flurry": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hamster:Graham": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hamster:Hamlet": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hamster:Hamphrey": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hamster:Holden": {
		game.NewLeaf,
	},
	"hamster:Rodney": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hamster:Soleil": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hedgehog:Label": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hedgehog:Mabel": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hedgehog:Sable": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hippo:Bertha": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hippo:Biff": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hippo:Bitty": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"hippo:Bubbles": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hippo:Clara": {
		game.DoubutsuNoMoriEPlus,
	},
	"hippo:Harry": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hippo:Hippeux": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hippo:Lulu": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"hippo:Rocco": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"hippo:Rollo": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"horse:Annalise": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Buck": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Cleo": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"horse:Clyde": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Colton": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Ed": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Elmer": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Epona": {
		game.NewLeaf,
	},
	"horse:Filly": {
		game.NewLeaf,
		game.HappyHomeDesigner,
	},
	"horse:Julian": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Papi": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Peaches": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Reneigh": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"horse:Roscoe": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Savannah": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Victoria": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"horse:Winnie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"kangaroo:Astrid": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"kangaroo:Carrie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.PocketCamp,
	},
	"kangaroo:Kitt": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"kangaroo:Koharu": {
		game.DoubutsuNoMoriEPlus,
	},
	"kangaroo:Marcie": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"kangaroo:Marcy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"kangaroo:Mathilda": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"kangaroo:Rooney": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"kangaroo:Sylvia": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"kangaroo:Valise": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"kangaroo:Walt": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"koala:Alice": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"koala:Canberra": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"koala:Eugene": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"koala:Faith": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.NewHorizons,
		game.PocketCamp,
	},
	"koala:Gonzo": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"koala:Huggy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"koala:Lyman": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"koala:Melba": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"koala:Ozzie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"koala:Sydney": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"koala:Yuka": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"lion:Aziz": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"lion:Bud": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"lion:Elvis": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"lion:Jubei": {
		game.DoubutsuNoMoriEPlus,
	},
	"lion:Leopold": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"lion:Lionel": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"lion:Mott": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"lion:Rex": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"lion:Rory": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mole:DonResetti": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"mole:MrResetti": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"monkey:Champ": {
		game.WildWorld,
		game.CityFolk,
	},
	"monkey:Deli": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"monkey:Elise": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"monkey:Flip": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"monkey:Monty": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"monkey:Nana": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"monkey:Porter": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"monkey:Shari": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"monkey:Simon": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"monkey:Tammi": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Anicotti": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Bella": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Bettina": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Bree": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Broccolo": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Candi": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"mouse:Carmen": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Chadder": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Chico": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"mouse:Dora": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Flossie": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
	},
	"mouse:Greta": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Limberg": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Moose": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Penelope": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Penny": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"mouse:Rizzo": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Rod": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"mouse:Samson": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"octopus:Inkwell": {
		game.NewLeaf,
	},
	"octopus:Marina": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"octopus:Octavian": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"octopus:Zucker": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"ostrich:Blanche": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"ostrich:Cranston": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"ostrich:Flora": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"ostrich:Gladys": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"ostrich:Julia": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"ostrich:Nindori": {
		game.DoubutsuNoMoriEPlus,
	},
	"ostrich:Phil": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"ostrich:Phoebe": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"ostrich:Queenie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"ostrich:Rio": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewHorizons,
		game.PocketCamp,
	},
	"ostrich:Sandy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"ostrich:Sprocket": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"otter:Lottie": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"otter:Lyle": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"otter:Pascal": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"owl:Blathers": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"owl:Celeste": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"panther:Katrina": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"peacock:Pave": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pelican:Pelly": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pelican:Pete": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pelican:Phyllis": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"penguin:Analog": {
		game.DoubutsuNoMoriEPlus,
	},
	"penguin:Aurora": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Boomer": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Cube": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Flo": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Friga": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Gwen": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Hopper": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Iggly": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Nobuo": {
		game.DoubutsuNoMoriEPlus,
		game.NewHorizons,
		game.PocketCamp,
	},
	"penguin:Puck": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Roald": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Sprinkle": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Tex": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"penguin:Wade": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"pig:Agnes": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Boris": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"pig:Chops": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Cobb": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Curly": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Gala": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Ganon": {
		game.NewLeaf,
	},
	"pig:Hambo": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"pig:Hugh": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Kevin": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Lucy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Maggie": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"pig:Pancetti": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Peggy": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Pigleg": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
	},
	"pig:Rasher": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:Spork": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pig:SueE": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"pig:Truffles": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"pigeon:Brewster": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Bonbon": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Bunnie": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Carmen": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Chrissy": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Claude": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.PocketCamp,
	},
	"rabbit:Coco": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Cole": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Doc": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Dotty": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Francine": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Gabi": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Gaston": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Genji": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Hopkins": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"rabbit:Mira": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:OHare": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Pippy": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Ruby": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Snake": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Tiffany": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rabbit:Toby": {
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"rabbit:ZipperTBunny": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"raccoon:TomNook": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"reindeer:Jingle": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rhinoceros:Hornsby": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"rhinoceros:Merengue": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rhinoceros:Patricia": {
		game.DoubutsuNoMoriEPlus,
	},
	"rhinoceros:Petunia": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"rhinoceros:Renee": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rhinoceros:Rhonda": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rhinoceros:Spike": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"rhinoceros:Tank": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"rhinoceros:Tiara": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"seagull:Gullivarrr": {
		game.NewHorizons,
	},
	"seagull:Gulliver": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Baabara": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Cashmere": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"sheep:Curlos": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Dom": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"sheep:Etoile": {
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"sheep:Eunice": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Frita": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Gen": {
		game.DoubutsuNoMoriEPlus,
	},
	"sheep:Muffy": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Pietro": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Stella": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"sheep:Timbra": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Vesta": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Wendy": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Willow": {
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sheep:Woolio": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
	},
	"skunk:Kicks": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"sloth:Leif": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:AgentS": {
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Blaire": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Cally": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Caroline": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Cece": {
		game.NewLeaf,
		game.NewHorizons,
	},
	"squirrel:Filbert": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Hazel": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Kit": {
		game.DoubutsuNoMoriEPlus,
	},
	"squirrel:Marshal": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Mint": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Nibbles": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Peanut": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Pecan": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Poppy": {
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Ricky": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Sally": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Shaki": {},
	"squirrel:Sheldon": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Static": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"squirrel:Sylvana": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"squirrel:Tasha": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"squirrel:Viche": {
		game.NewLeaf,
		game.NewHorizons,
	},
	"tapir:Luna": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"tiger:Bangle": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"tiger:Bianca": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"tiger:Claudia": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"tiger:Leonardo": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"tiger:Rolf": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"tiger:Rowan": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"tiger:Tybalt": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"tortoise:Cornimer": {
		game.WildWorld,
		game.NewLeaf,
		game.NewHorizons,
	},
	"tortoise:Tortimer": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"turkey:Franklin": {
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"turtle:Grams": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"turtle:Kappn": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"turtle:Leila": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"turtle:Leilani": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"walrus:Wendell": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
	},
	"wolf:Audie": {
		game.NewHorizons,
		game.PocketCamp,
	},
	"wolf:Chief": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"wolf:Dobie": {
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"wolf:Fang": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"wolf:Freya": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"wolf:Kyle": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"wolf:Lobo": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"wolf:Skye": {
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"wolf:Tarou": {
		game.DoubutsuNoMoriEPlus,
	},
	"wolf:Vivian": {
		game.DoubutsuNoMoriEPlus,
		game.NewLeaf,
		game.NewHorizons,
		game.PocketCamp,
	},
	"wolf:WLink": {
		game.NewLeaf,
	},
	"wolf:Whitney": {
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
	"wolf:Wolfgang": {
		game.DoubutsuNoMori,
		game.DoubutsuNoMoriPlus,
		game.AnimalCrossing,
		game.DoubutsuNoMoriEPlus,
		game.DongwuSenlin,
		game.WildWorld,
		game.CityFolk,
		game.NewLeaf,
		game.NewHorizons,
		game.HappyHomeDesigner,
		game.AmiiboFestival,
		game.PocketCamp,
	},
}
