name: pull_request

on:
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          os:
            - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  test:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        go-version:
          - '1.23.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version: ${{ matrix.go-version }}
      - run: go install golang.org/x/lint/golint@latest
      - run: golint -set_exit_status ./...
      - run: go test ./...
