name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  main:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
